### ISSUE TITLE
very good plugin for hexo next theme

### ISSUE THREAD

**Issue by abmn614** [qzchenwl/hexo-generator-author#3]
The title in author page displays english word 'title.author'.
I found a way to change it to chinese by adding a line in the title field to file /language/zh-Hans.yml :
author: 作者

**Comment by qzchenwl** [comment]
You are right. But this configuration does not belong to this project. 

The title of author page is defined as `__('title.author')` in the following example. You can change it and the corresponding language config. All of these belong to the theme you use.

File: `themes/next/layout/author.swig`

``` swig
{% extends '_layout.swig' %}
{% import '_macro/post-collapse.swig' as post_template %}
{% import '_macro/sidebar.swig' as sidebar_template %}

{% block title %} {{ __('title.author') }}: {{ page.author }} | {{ config.title }} {% endblock %}

{% block content %}

  <section id="posts" class="posts-collapse">
    <div class="collection-title">
      <h2 >
        {{ page.author }}
        <small>{{  __('title.author')  }}</small>
      </h2>
    </div>

    {% for post in page.posts %}
      {{ post_template.render(post) }}
    {% endfor %}
  </section>

  {% include '_partials/pagination.swig' %}

{% endblock %}

{% block sidebar %}
  {{ sidebar_template.render(false) }}
{% endblock %}
```

File: `themes/next/languages/zh-Hans.yml`

``` yaml
title:
  archive: 归档
  category: 分类
  tag: 标签
  author: 作者

```
